version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - sql_data:/var/opt/mssql

  sftp:
    image: atmoz/sftp
    container_name: sftp
    command: user:password:1001
    ports:
      - "2222:22"
    networks:
      - backend
    volumes:
      - ./sftp-data:/home/demo/upload

  datasyncapi:
    image: datasync-api   # Or use build: . if you want Docker to rebuild
    container_name: datasyncapi
    build: .
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=DataSyncDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      SftpConfig__Host: "sftp"
      SftpConfig__Port: "22"
      SftpConfig__Username: "user"
      SftpConfig__Password: "password"
      SftpConfig__RemoteFolder: "/home/demo/upload"
    depends_on:
      - sqlserver
      - sftp
    networks:
      - backend

networks:
  backend:

volumes:
  sql_data: